FROM golang:1.21.6-alpine3.19 as builder_arm64
ONBUILD ADD https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-aarch_64.zip /root/protoc.zip

FROM golang:1.21.6-alpine3.19 as builder_amd64
ONBUILD ADD https://github.com/protocolbuffers/protobuf/releases/download/v25.2/protoc-25.2-linux-x86_64.zip /root/protoc.zip

FROM builder_${BUILDARCH}
RUN <<EOF
apk update && apk add unzip && rm -vrf /var/cache/apk/*
unzip -o /root/protoc.zip -d /usr/local bin/protoc
unzip -o /root/protoc.zip -d /usr/local 'include/*'
rm /root/protoc.zip
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.32
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.19.0
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.19.0
go install github.com/envoyproxy/protoc-gen-validate@v1.0.4
go clean -modcache
go clean -cache
EOF
